config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#index'

  get 'dashboards/index'
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :profiles
  resources :clients
  resources :vendors
  devise_for :users
  
  resources :projects do
    resources :tasks
end
  

end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
has_many :tasks

validates_presence_of :fullname, :gender, :d_o_b, :designation, :user_id
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:title, :fullname, :gender, :designation, :d_o_b, :task_id, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, %w[Male Female] %>
  </div>
  <div class="field">
    <%= f.label :designation %><br>
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :d_o_b %><br>
    <%= f.date_select :d_o_b %>
  </div>
  
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :email, prompt: "Select user" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Fullname</th>
      <th>Gender</th>
      <th>Designation</th>
      <th>D o b</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.title %></td>
        <td><%= profile.fullname %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.designation %></td>
        <td><%= profile.d_o_b %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %> |
<%= link_to 'Dashboard', dashboards_index_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @profile.title %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @profile.fullname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @profile.designation %>
</p>

<p>
  <strong>D o b:</strong>
  <%= @profile.d_o_b %>
</p>


<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>

<h3>Assigned Tasks</h3>

<ul>
  <% for task in @profile.tasks %>
    <li><%= link_to task.name, task_path(task) %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>