config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#index'

  get 'dashboards/index'
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :profiles
  resources :clients
  resources :vendors
  devise_for :users
  
  resources :projects do
    resources :tasks
end
  

end

app/models/client.rb
class Client < ActiveRecord::Base

has_many :projects
belongs_to :user

before_destroy :delete_child
validates_presence_of :name, :company, :email, :web, :phone
validates_numericality_of :phone 
validates_length_of :phone, is: 10
validates_uniqueness_of :email, :company
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

def list
Project.where('client_id =?',id)
end
def list_name
Project.where('client_id =?',id).pluck(:name)
end


private 
def delete_child

@projects = Project.where("client_id = ?", id)
for project in @projects
Task.where("project_id =?" , project.id).delete_all
end
 Project.where("client_id = ?", id).delete_all
end


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :find_record, only: [:show, :edit, :update, :destroy] 
  # GET /clients
  # GET /clients.json
  def index
    @clients = (current_user.role? "admin") ? Client.all : current_user.clients

  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @client.user_id = current_user.id

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_client
      @client = Client.find(params[:id])
    end

  def find_record
  begin
    @client = current_user.clients.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, notice: "Record Doesn't exist"
  end
end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :company, :email, :web, :phone, :user_id)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :email, prompt: "Select user" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Email</th>
      <th>Web</th>
      <th>Phone</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.company %></td>
        <td><%= client.email %></td>
        <td><%= client.web %></td>
        <td><%= client.phone %></td>
        <td><%= client.user_id %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Client.new %>
<%= link_to 'New Client', new_client_path %> <% end %>|
<%= link_to 'Dashboard', dashboards_index_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @client.company %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Web:</strong>
  <%= @client.web %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>User:</strong>
  <%= @client.user_id %>
</p>

<% if can? :update, @client %>
  <%= link_to "Edit", edit_client_path %> <% end %>| 
<% if can? :destroy, @client %>
  <%= link_to "Delete", client_path(@client), method: :delete, data: {confirm: "Are you sure?"} %> 
<% end %>


<%= link_to 'Back', clients_path %>