config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#index'

  get 'dashboards/index'
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :profiles
  resources :clients
  resources :vendors
  devise_for :users
  
  resources :projects do
    resources :tasks
end
  

end

app/models/project.rb
class Project < ActiveRecord::Base

has_many :tasks
has_many :project_categories
has_many :categories, through: :project_categories
belongs_to :user
belongs_to :client

#validates_presence_of :title, :location, :status, :start_date, :client_id, :description, :user_id
#validates_presence_of :start_date, message: "should be selected"
#validates_numericality_of :client_id, :user_id
#validates_uniqueness_of :title, scope_to: :client_id
#validate :check_start_date



def details
	"#{assigned_to} - #{status} - #{start_date} - #{description} - #{location} - #{Client.find(client_id).name}"
end

def self.show_projects(start_date,end_date)
	Project.where('start_date >= ? AND start_date <= ?', start_date,end_date)
end

def self.completed
	Task.where("is_completed = ?", true)

end

def self.incomplete
	Task.where("is_completed = ?", false)

end

def self.overdue(date)
	Task.where("due_date < ? AND is_completed = ?", date,false)

end

def self.completed_project(project)
	project.tasks.where("is_completed = ?", true)

end

def self.incomplete_project(project)
  project.tasks.where("is_completed = ?", false)
end

def self.overdue_project(date,project)
	project.tasks.where("due_date < ? AND is_completed = ?", date,false)
  
end
 private


 def check_start_date
if !self.start_date.nil? && self.start_date < Date.today
	errors.add(:start_date, "Date is invalid. Should not be less than #{Date.today}")
 end
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :find_record, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index

    @projects = (current_user.role? "admin") ? Project.all : current_user.projects
    
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
      @project = (current_user.role? "admin") ? Project.find(params[:id]) : current_user.projects.find(params[:id])

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :location, :start_date, :status, :assigned_to, :user_id, :client_id)
    end

    def find_record
    begin
      @project = current_user.projects.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, notice: "Record Doesn't exist"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 10, cols: 50 %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, %w[new on-going completed not-started] %>
  </div>
  <div class="field">
    <%= f.label :assigned_to %><br>
    <%= f.select :status, %w[Design Site-Inspection Quality Reports] %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :email, prompt: "Select user" %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.collection_select :client_id, Client.all, :id, :company, prompt: "Select Client" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<% data = {} %>

<% Client.all.each do |client| %>
  <% data["#{client.name}"] = client.projects.size %>
  <% end %>

<%= pie_chart(data) %>

<% projects = {} %>

<% Project.all.each do |project| %>
  <% projects["#{project.title}"] = project.tasks.size %>
  <% end %>

  <%= column_chart(projects) %> 

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start date</th>
      <th>Status</th>
      <th>Assigned to</th>
      <th>User</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.location %></td>
        <td><%= project.start_date.strftime("%A, %d %B %Y") %></td>
        <td><%= project.status %></td>
        <td><%= project.assigned_to %></td>
        <td><%= project.user_id %></td>
        <td><%= project.client_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Client.new %>
<%= link_to 'New Project', new_project_path %> <% end %>|
<%= link_to 'Dashboard', dashboards_index_path %> |<%= link_to "Export excel", projects_path(format: "xls") %>

app/views/projects/index.xls.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start date</th>
      <th>Status</th>
      <th>Assigned to</th>
      <th>User</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.location %></td>
        <td><%= project.start_date.strftime("%A, %d %B %Y") %></td>
        <td><%= project.status %></td>
        <td><%= project.assigned_to %></td>
        <td><%= project.user_id %></td>
        <td><%= project.client_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= link_to @project.title, projects_path %>
</p>
<div class="container">
<p>
  <strong>Details</strong>
  <%= @project.details %>
</p>
</div>

<%= link_to 'Edit', edit_project_path(@project) %> | <%= link_to 'Back', projects_path %>

<div class="container">

<h3> Add task </h3>

<%= form_for ([@project,@project.tasks.build]) do |f| %>

  <label>Name: </label><br/>
  <%= f.text_field :name %><br/>

  <label>Due Date: </label><br/>
  <%= f.date_select :due_date %><br/>

  <label>Is completed? </label><br/>
  <%= f.check_box :is_completed %><br/>

  <label>Rating: </label><br/>
  <%= f.select :rating, %w[1 2 3 4 5] %><br/>

  <label>Assigned To: </label><br/>
  <%= f.collection_select :profile_id, Profile.all, :id, :fullname %><br/>

  <%= f.hidden_field :project_id, value: @project.id %>
  
  <%= f.submit%>
<% end %>

</div>

<div class="container">
  <% tasks = @project.tasks %>
<h3> Total tasks - <%= tasks.size %></h3>

<% over_due_tasks = tasks.where('is_completed = ? AND due_date < ?', false, Date.today) %>
<% incomplete_tasks = tasks.where('is_completed = ? AND due_date >= ?', false, Date.today) %>
<% completed_tasks = tasks.where('is_completed = ?', true) %>

<% data = {"completed" => completed_tasks.size, "incomplete" => incomplete_tasks.size, "over_due" => over_due_tasks.size} %>

<%= pie_chart(data) %>

<% dates = [] %>
<% @project.tasks.order('due_date').each do |task| %>
<% dates.push(["#{task.name}", (@project.start_date > task.due_date - 6.days) ? @project.start_date : (task.due_date - 6.days), task.due_date]) %>
<% end %>

<%= timeline(dates) %>

</div>
<div class="container"> 

  <% over_due_tasks = tasks.where('is_completed = ? AND due_date < ?', false, Date.today) %>
<h3> Overdue tasks </h3>
<ul>
  <% for task in over_due_tasks %>
  <li><%= task.name %> <small><%= time_ago_in_words(task.due_date) %> ago </small></li>
  <% end %>
</ul>

  <% incomplete_tasks = tasks.where('is_completed = ? AND due_date >= ?', false, Date.today) %>
<h3> Incomplete tasks </h3>
<ul>
  <% for task in incomplete_tasks %>
  <li><%= task.name %> <small><%= time_ago_in_words(task.due_date) %> from now </small>
  <%= link_to "mark as complete", tasks_mark_as_complete_path(task_id: task.id) %></li>
  <% end %>
</ul>

  <% completed_tasks = tasks.where('is_completed = ?', true) %>
<h3> Completed tasks </h3>
<ul>
  <% for task in completed_tasks %>
  <li><%= task.name %> <small><%= time_ago_in_words(task.updated_at) %> 
  <%= task.updated_at < Time.now ? "ago" : "from now" %>
   </small>
  <%= link_to "mark as incomplete", tasks_mark_as_incomplete_path(task_id: task.id) %></li>
  <% end %>
</ul>
</div>

<% if can? :update, @client %>
  <%= link_to "Edit", edit_project_path %> <% end %>| 
<% if can? :destroy, @client %>
  <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %> 
<% end %> |

  <%= link_to 'Dashboard', dashboards_index_path %> |