config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#index'

  get 'dashboards/index'
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'

  resources :profiles
  resources :clients
  resources :vendors
  devise_for :users
  
  resources :projects do
    resources :tasks
end
  

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

belongs_to :user

validates_presence_of :name, :company, :email, :web, :phone, :is_po_released
validates_numericality_of :phone 
validates_length_of :phone, is: 10
validates_uniqueness_of :email, :company
validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  before_action :find_record, only: [:show, :edit, :update, :destroy]
  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = (current_user.role? "admin") ? Vendor.all : current_user.vendors
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
      @vendor = (current_user.role? "admin") ? Vendor.find(params[:id]) : current_user.vendors.find(params[:id])

  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :company, :email, :web, :phone, :is_po_released, :user_id)
    end

    def find_record
  begin
    @vendor = current_user.vendors.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, notice: "Record Doesn't exist"
  end
end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :is_po_released %><br>
    <%= f.check_box :is_po_released %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :email, prompt: "Select user" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vendors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Email</th>
      <th>Web</th>
      <th>Phone</th>
      <th>Is po released</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.name %></td>
        <td><%= vendor.company %></td>
        <td><%= vendor.email %></td>
        <td><%= vendor.web %></td>
        <td><%= vendor.phone %></td>
        <td><%= vendor.is_po_released %></td>
        <td><%= vendor.user_id %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %> |
<%= link_to 'Dashboard', dashboards_index_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @vendor.company %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vendor.email %>
</p>

<p>
  <strong>Web:</strong>
  <%= @vendor.web %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vendor.phone %>
</p>

<p>
  <strong>Is po released:</strong>
  <%= @vendor.is_po_released %>
</p>

<p>
  <strong>User:</strong>
  <%= @vendor.user_id %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>